NEW: start transfer/cover/modify visualisation & update pre-merge

diff --git a/.github/workflows/pre_merge.yml b/.github/workflows/pre_merge.yml
--- a/.github/workflows/pre_merge.yml
+++ b/.github/workflows/pre_merge.yml
@@ -37,26 +37,31 @@ jobs:
         run: |
           pip install pytest
           pip install pytest-cov
-      - name: Run pytest
+      - name: Run pytest with coverage report
         run:
-          python3 -m pytest
-  
-  coverage:
+          python3 -m pytest --cov-report term --cov=src/corpus_distance
+
+
+  check-version-change:
     runs-on: ubuntu-latest
     needs:
+      - pylint
       - tests
     steps:
       - name: Checkout repo
         uses: actions/checkout@v4
-      - name: Install dependencies
+      - name: fetch repo
         run: |
-          python -m pip install --upgrade pip
-          pip install -r requirements.txt
-          pip install -e .
-      - name: Install pytest
+          git fetch origin ${{ github.event.pull_request.base.ref }}
+      - name: get versions
         run: |
-          pip install pytest
-          pip install pytest-cov
-      - name: Run pytest with coverage report
-        run:
-          python3 -m pytest --cov-report term --cov=src/corpus_distance
+          PREVIOUS_VER=$(git show FETCH_HEAD:pyproject.toml | grep -E '^version = ' | head -n 1 | cut -d '"' -f 2)
+          CURRENT_VER=$(grep -E '^version = ' pyproject.toml | head -n 1 | cut -d '"' -f 2)
+      - name: compare versions
+        run: |
+          if [ "$PREVIOUS_VER" = "$CURRENT_VER" ]; then
+            echo "Error: Package version has not been bumped!"
+            exit 1
+          else
+            echo "Success: Version $PREVIOUS_VER has been bumped to $CURRENT_VER!"
+          fi
